### ISSUE TITLE
Indicate more clearly that a node is collapsed

### ISSUE THREAD

**Issue by ThHarbig** [Integrative-Transcriptomics/Evidente2.0#13]
- Right now it's only implied by the label
- We could make the node bigger

**Comment by mwittep** [comment]
Ideas and steps: 

Normalize barcharts
Add Whitespace around barcharts and boxplots
change circle to triangle (similar as Evidente 1)
Have a higher Rowheight for collapsed nodes

**Comment by mwittep** [comment]
closed in #69
