### ISSUE TITLE
Dragging Improvement

### ISSUE THREAD

**Issue by ThHarbig** [Integrative-Transcriptomics/Evidente2.0#23]
Improve dragging:

When dragging too much might be happening at once. E.g I only want to move the tree up/down but simultaneously the heatmap component is dragged to the left or right or the other way around: I want to move the heatmap to the left/right but it also moves up/down

Only allow dragging when it is useful: 
- If entire tree is visible don't allow dragging up or down
- only drag heatmap when mouse is over heatmap cells, not over lines
- Maybe provide fixed drag handles instead of dragging always?

**Comment by mwittep** [comment]
closed by #54
